FROM python:3.11-slim

WORKDIR /app


COPY . /app


RUN pip install --no-cache-dir fastapi==0.103.1 uvicorn==0.23.2 pandas==2.1.1 numpy==1.26.0 scikit-learn==1.3.0 joblib==1.3.2 pydantic==2.3.0

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]


#docker build -t btc_api .
#docker run -p 8000:8000 btc_api

