FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn pandas numpy scikit-learn joblib pydantic

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]


#docker build -t btc_api .
#docker run -p 8000:8000 btc_api

